### ISSUE TITLE
Default rc.lua.template suggestions

### ISSUE THREAD

**Issue by ngoonee** [lcpz/awesome-copycats#199]
I'm just trying this out, long time awesome user who realized my rc.lua was way too messy for productive use....

Anyway, I like that the template has both focus.byidx and focus.bydirection (I use the latter myself, most times). However this does not seem to carry over to layout manipulation. In particular if modkey+j changes focus downwards, it would make sense that modkey+shift+j swaps clients downards rather than using id.

I recommend using awful.client.swap.global_bydirection for modkey+shift+{j,k,l,h} and using altkey+{j,k} for the current swap.byidx lines.

**Comment by lcpz** [comment]
The point is that layout manipulation shortcuts are from default `rc.lua`, where mod4+shift+{l,h} are already assigned. Since this is a template, it is reasonable to keep it compatible with default configuration as much as possible.

Users can then do customisations like yours, instead of re-learning keys.

**Comment by ngoonee** [comment]
Okay fair point. Was figuring since you do add directional keys it may make sense to adjust the layout commands accordingly.

**Comment by lcpz** [comment]
If you find combinations for `global_bydirection` which are comfortable for you and don't overwrite existing keys, I can add them.
