### ISSUE TITLE
Tag layouts problem

### ISSUE THREAD

**Issue by hrzhu** [lcpz/awesome-copycats#213]
These are my tag configs
```
awful.util.tagnames = { "term", "dev", "dev2", "firefox", "chrome", "im", "media" }
awful.layout.layouts = {
    awful.layout.suit.tile.left,
    awful.layout.suit.tile,left,
    awful.layout.suit.tile.left,
    awful.layout.suit.floating,
    awful.layout.suit.floating,
    awful.layout.suit.max,
    awful.layout.suit.max,
}
```
I expect the tags to have the layouts in listed order but they are not. The first 4 tags are tile though they are not all tile.left. The 5th and 6th are floating and the 7th is max. And I can no longer toggle a tag layout if it's floating. 

I only did some minor modification like removing the freedesktop thing and changing some keyboard shortcuts. This is my whole [rc.lua](http://paste.ubuntu.com/25871708/). I made no changes to the theme except changing date output format.
```
awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: 
 • execinfo support: 
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```
I have another problem. I've installed `xfonts-terminus` but awesome is not using it.

**Comment by lcpz** [comment]
Can you test your tag configuration with `/etc/xdg/awesome/rc.lua` and see if the issue persists?

Anyway, to solve it, instead of duplicating `layouts`, set it like this:

```lua
awful.util.tagnames = { "term", "dev", "dev2", "firefox", "chrome", "im", "media" }
awful.layout.layouts = {
    awful.layout.suit.tile.left,
    awful.layout.suit.floating,
    awful.layout.suit.max,
}
```

Then, in your `theme.lua` change [this line](https://github.com/lcpz/awesome-copycats/blob/master/themes/powerarrow-dark/theme.lua#L271) like this:

```diff
-awful.tag(awful.util.tagnames, s, awful.layout.layouts)
+local layouts = awful.layout.layouts
+awful.tag(awful.util.tagnames, s, { layouts[1], layouts[1], layouts[1], layouts[2], layouts[2], layouts[3], layouts[3] }) 
```

About Terminus, set [this line](https://github.com/lcpz/awesome-copycats/blob/master/themes/powerarrow-dark/theme.lua#L17) to just "Terminus 9" or whatever the font ID is under Ubuntu.

**Comment by hrzhu** [comment]
Thanks. Removing duplicated layouts solved the problem.
