### ISSUE TITLE
holo: replicate old taglist background focus image

### ISSUE THREAD

**Issue by initrider** [lcpz/awesome-copycats#230]
Hello. That's your old theme - https://camo.githubusercontent.com/b05bcb5788aeb916273c48df251107300c621f5e/687474703a2f2f646f7473686172652e69742f7075626c69632f696d616765732f75706c6f6164732f3632312e706e67
Each tag in taglist widget has line under it`s name, when it's active. And this line fills at full lenght of tag, but how to make this line, for example, for 90% of tag's lenght or with space for 10 px on both sides. Here is, that I am talking about:
![res](https://user-images.githubusercontent.com/35081987/38453988-7c5fde64-3a67-11e8-8729-bedbce9ff46a.png)

**Comment by lcpz** [comment]
You can replicate it by placing [this file](https://github.com/lcpz/awesome-copycats/blob/23dec83ad5e93be820f4a37b1bca9270b2acc92c/themes/holo/icons/taglist_bg_focus.png) in `$HOME/.config/awesome/themes/holo` and adding [this line](https://github.com/lcpz/awesome-copycats/blob/23dec83ad5e93be820f4a37b1bca9270b2acc92c/themes/holo/theme.lua#L27) to your `theme.lua`. Since it's a simple PNG, you have to manually edit in order to make it fit the desired length.

If you want to make a clean job using the current API, you have to create a [`gears.surface`](https://awesomewm.org/doc/api/libraries/gears.surface.html) and feed it to [this variable](https://awesomewm.org/doc/api/classes/awful.widget.taglist.html#beautiful.taglist_squares_sel) in `theme.lua`. The surface has to be written in Cairo through Lua bindings: basically you have to create a [filled rectangle](http://zetcode.com/gfx/cairo/shapesfills/) with some offset. Maybe @Elv13 can kindly and help you on this one, as it is probably a common request.

**Comment by initrider** [comment]
Where can I ask him? (and, maybe he will do this work to me for money, because this stuff seems too complicated to me XD )

**Comment by Elv13** [comment]
/me Is everywhere

It's possible with or without messing with surfaces. In Awesome git-master, there is an API to define custom taglist/tasklist widgets with the normal syntax. No need for Cairo magic

See
https://awesomewm.org/apidoc/classes/awful.widget.taglist.html

**Comment by lcpz** [comment]
@initrider I just browsed the stable API and found the solution:

```lua
local underscore_shape = function(cr, width, height)
    gears.shape.transform(gears.shape.rectangle):translate(0, 20)(cr, width, height)
end
theme.taglist_squares_sel = gears.surface.load_from_shape(200, 22, underscore_shape, theme.fg_focus)
```

This code recreates the old taglist focus. You can reduce the `200` value as you like to make the underscore smaller. The only point is that the shape would be "aligned to the left", and I don't know if it is possible to "center" it in a clean way. @Elv13 any idea?

**Comment by lcpz** [comment]
> The only point is that the shape would be "aligned to the left", and I don't know if it is possible to "center" it in a clean way.

The shape is independent of the taglist, so we can't use a tag's size to adapt the shape as requested.

Probably the only thing currently possible is to set the same size for each tag, plus increase `offset` and decrease `dimension` in the following code as you like.

```lua
local offset, dimension = 0, 200
local underscore_shape = function(cr, width, height)
    gears.shape.transform(gears.shape.rectangle):translate(0, 20)(cr, width, height)
end
theme.taglist_squares_sel = gears.surface.load_from_shape(200, 22, underscore_shape, theme.fg_focus)
```

One way to make the tag entries share the same size is to use a monospaced font, and add spaces wherever needed. For instance:

```lua
awful.util.tagnames = { "   WEB   ", "TERMINALS", "  FILES  ", "  OTHER  " }
```

The other possible way is to use ad-hoc fonts, or images.
