### ISSUE TITLE
how to adjust the tagbar height?

### ISSUE THREAD

**Issue by CDitzel** [lcpz/awesome-copycats#233]
the tagbar looks rather squeezed, but I cant seem to find the property in rc.lua that lets me adjust the height,

please help

**Comment by lcpz** [comment]
Looking at the [stable API](https://awesomewm.org/doc/api/classes/awful.widget.taglist.html#awful.taglist), it seems that you can't adjust the taglist, since it is a widget incorporated into the wibar.

If you want to change your [wibar's height](https://awesomewm.org/doc/api/classes/awful.wibar.html#awful.wibar.height), look for `awful.wibar` in `theme.lua`.

This is where you can find it in [multicolor](https://github.com/lcpz/awesome-copycats/blob/master/themes/multicolor/theme.lua#L282).
