### ISSUE TITLE
Dmenu makes tag disappear

### ISSUE THREAD

**Issue by deadsidestar** [lcpz/awesome-copycats#262]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Best way I could explain this:

Ever since the migration to awesome 4.x, when you spawn dmenu, one of the tags (workspaces) disappears. But if there is something else like a terminal on that work space (tag) it doesn't seem to happen. Only on a blank work space. This also doesn't happen in the last version of awesome 3.5.9

way to reproduce:

This happens on any theme used
move to a work space with nothing on it, spawn dmenu, and select an application, once it opens check the tags...one tag will be lost. But when you reload awesome the tag comes visable again

**Comment by lcpz** [comment]
I can't reproduce.

Does this happen with default Awesome theme as well?

Can you make a video, or link me your configurations?

**Comment by deadsidestar** [comment]
It doesn't happen on awesome default config.
here it the links to my configs, I wil try to make a video tomorrow.
https://github.com/deadsidestar/awesome

**Comment by arcolinuxz** [comment]
I experience this too.

This is the look at first.

![good](https://user-images.githubusercontent.com/36679406/57174690-09ee7f00-6e43-11e9-9704-7504966f06ae.png)

After accessing the dmenu several times the active workspace number disappears from the menu bar.
Then you get this.
![bad](https://user-images.githubusercontent.com/36679406/57174701-2be80180-6e43-11e9-98ac-cf072c1b0dd9.png)

Ofcourse people report we have a bug or an issue since they their workspaces disappear. We try to avoid this issue by using rofi as a launch application. But that is not really a solution.
Here is a video showing the issue

https://vimeo.com/arcolinux/review/334117466/b17384f1d4
Password to see it is : awesome

Hope you can replicate it. This is the iso that we are using. ArcoLinux- Awesome

https://master.seedhost.eu/arcolinux/iso/

**Comment by deadsidestar** [comment]
it was a keybinding issue after all, closing issue
